services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: false
    networks:
      - infra

networks:
  infra:
    name: infra-datasynk
    external: true  